// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/proto/v1/story.proto

package apiv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Fact with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Fact) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Fact with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in FactMultiError, or nil if none found.
func (m *Fact) ValidateAll() error {
	return m.validate(true)
}

func (m *Fact) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Title

	// no validation rules for Category

	// no validation rules for Summary

	// no validation rules for WikiUrl

	// no validation rules for ImgUrl

	if len(errors) > 0 {
		return FactMultiError(errors)
	}

	return nil
}

// FactMultiError is an error wrapping multiple validation errors returned by
// Fact.ValidateAll() if the designated constraints aren't met.
type FactMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FactMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FactMultiError) AllErrors() []error { return m }

// FactValidationError is the validation error returned by Fact.Validate if the
// designated constraints aren't met.
type FactValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FactValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FactValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FactValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FactValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FactValidationError) ErrorName() string { return "FactValidationError" }

// Error satisfies the builtin error interface
func (e FactValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFact.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FactValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FactValidationError{}

// Validate checks the field values on GetFactResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetFactResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetFactResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetFactResponseMultiError, or nil if none found.
func (m *GetFactResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetFactResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetFact()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetFactResponseValidationError{
					field:  "Fact",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetFactResponseValidationError{
					field:  "Fact",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFact()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetFactResponseValidationError{
				field:  "Fact",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetFactResponseMultiError(errors)
	}

	return nil
}

// GetFactResponseMultiError is an error wrapping multiple validation errors
// returned by GetFactResponse.ValidateAll() if the designated constraints
// aren't met.
type GetFactResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetFactResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetFactResponseMultiError) AllErrors() []error { return m }

// GetFactResponseValidationError is the validation error returned by
// GetFactResponse.Validate if the designated constraints aren't met.
type GetFactResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetFactResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetFactResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetFactResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetFactResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetFactResponseValidationError) ErrorName() string { return "GetFactResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetFactResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetFactResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetFactResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetFactResponseValidationError{}
